# Site Settings
lang: en
title: bolero2.log
tagline: bolero2.log
email: sheocjf1025@gmail.com
description: >
  ""
baseurl: ""
url: "https://bolero2.dev"
permalink: pretty
favicon: /favicon.png
gh_sponsor: bolero2
#hide_share_buttons: true
#theme_color: '#eeeeee'
fixed_navbar: top
# direction: one of <ltr, rtl, auto>, default: ltr
direction: ltr

paginate: 3
paginate_path: "/blog/page:num"
# theme: "bulma-clean-theme"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: bolero2


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: 3563142385

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "bolero2"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: false     # Latest post 보여줌
      menubar_toc: true       # 왼쪽에 1. ~~~ , 2. ~~~ 이런거 제목 생기는거
      toc: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
