# Site Settings
lang: en
title: bolero2.log
tagline: bolero2.log
email: sheocjf1025@gmail.com
description: >
  ""
baseurl: ""
url: "https://bolero2.dev"
permalink: pretty
favicon: /favicon.png
gh_sponsor: bolero2
# theme_color: '#'
# hide_share_buttons: true
# theme_color: '#ff0000'
# theme_color: '#000000'
fixed_navbar: lrt
# direction: one of <ltr, rtl, auto>, default: ltr
direction: ltr

paginate: 3
paginate_path: "/blog/page:num"
# theme: "bulma-clean-theme"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: bolero2.disqus.com


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-228665215-2

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "bolero2"
      layout: post
      # image: https://via.placeholder.com/800x600
      show_sidebar: true     # /blog sidebar -> /blog/index.html, 이거는 각 post 내에 사이드바 여부
      menubar_toc: true       # 페이지 왼쪽에 Contents[1. XXX | 2. XXX] 이런거 항목 이동 생기는거
      toc: true
      toc_title: "Contents"

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
